var GAME_LEVELS = [
  
  ["                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                           xxxx            xxxx          xxxx           ",
   "                                      xxxx                        xxxxxxx                                            xxxx               ",
   "                                     xx!!xxx                     xxxx     xxxx     xxxx             xxxx            xxxx                ",
   "                                  xxxxx!!xxxxxx       xxx     xx           xx                                    xxx                    ",
   "                                   xx!!!!!!!!!!!!!!          xx                                                xxx                      ",
   "                                       xxxxxxxxxx!!x        x                                                xxx                        ",
   "                                                xx!x        x                                             xxxx                          ",
   "                                                 x!x        x                                          xxxxxxxx                         ",
   "                                                x!x         x                 x                    xxxx!!!!!!!!!!!!!!!!                 ",
   "                                                  *          xx   xxx  xxx   xx  x              xxxxxxxxxxxxxxxxxxxxx *                 ",
   "                                                              xx!!!!!!!!!!!xx    xxxx         xxx                     *                 ",
   "                                                  *            xxxx!!!!!xxxx      xx         xx                       *                 ",
   "                                                                  xxxxxxx          x       xxxx                       *                 ",
   "                                                                                   x          x                       *                 ",
   "                                                                                   x          x                       *                 ",
   "                                                  *                                x          x                                         ",
   "                                                                                   xxxx       x                       *                 ",
   "                                                                                              x                       *                 ",
   "                                                                                           xxxx                                         ",
   "                                                                                                                                        ",
   "                                                  *                                                                                     ",
   "                      xxxx                                                                                                              ",
   "                    xxxxxx    xx    xx                        xxxxxxx     xxx     xxxxxxxxxxxxxxxxxxx                                   ",
   "                  xxxxxxxx    xx    xx                        xx                                                 xxxxx                  ",
   "     @          xxxxxxxxx     xx    xx                       xx                                                                         ",
   "    xxx       xxxxxxxxxxx     xx     x                     xxx                                            xxxxx        *  xxxxx         ",
   "    x x     xxxxxxxxxxxx      xx     xx                  xx                                                            *                ",
   "!!!!x x!!!!!xxxxxxxxxxxx!!!!!!xx      xx!!!!!!xxxx     xx                                                                               ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx        xxxxxxxxxx  *                                                                               xxxxx",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx                                                                                                         ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx                                                                                                         ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x                                                                                                          ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x                                                                                xxxx   xxxx    xxxxx      ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x                                        xxxxxxx   xxx   xxxxxxx     xxxxxx!!!!!!xxxx!!!xxxx!!!!xxxxx!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxxxx     xxxxxxx       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
